node default{

$content = "this is a file generated by puppet\n"

  file{'/tmp/test.txt':
    ensure  => file,
    content => $content,
    owner   => 'root',
  }
/* you can't declare the same resource name more than once in the same file because it will create amibigous configuration so the agent will throw an error
  file{'/tmp/test.txt':
    owner   => 'root',
  }
*/
}
